### PR TITLE
Correct the problem with the "none" option for parameter "type"

### PR DESCRIPTION
**Pull request by caffarel**
Change "none" option name to "no numbering"

### CODE REVIEW

**Comment by lovasoa** [comment]
why change it ?

**Review by lovasoa — CHANGES_REQUESTED** [review]
What is the problem with naming it "none" ?

**Comment by caffarel** [comment]
It wasn't working for me (wasn't recognized). I'm trying to see with friends if I'm the only one with that problem (I saw there was an issue that seemed like my problem but rereading it it seems it wasn't)

**Comment by lovasoa** [comment]
your problem was actually probably this: https://github.com/lovasoa/pagelabels-py/issues/12

**Comment by caffarel** [comment]
Oh yeah probably thank you !

**Pull request closed without merging**
